# conda env create --file environment.yml
# conda update create --file environment.yml
# conda activate UltraFastCat
# conda remove -n UltraFastCat
name: UltraFastCat
channels:
  - conda-forge
  - pytorch-nightly
  - defaults
dependencies:
  - imageio
  - jupyter
  - numpy
  - matplotlib
  - nbconvert
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - seaborn
  - pip
  - pip:
    - nltk
    - MotionClouds
